import { Hospital, Ambulance, Coordinates } from '../types';

export interface KarnatakaDistrictInfo {
  name: string;
  code: string;
  headquarters: string;
  center: Coordinates;
  taluks: string[];
}

export const KARNATAKA_DISTRICTS: KarnatakaDistrictInfo[] = [
  {
    name: 'Bengaluru Urban',
    code: 'KA-01/02/03/04/05/41/50/51/53',
    headquarters: 'Bengaluru',
    center: { lat: 12.9716, lng: 77.5946 },
    taluks: ['Bengaluru North', 'Bengaluru South', 'Bengaluru East', 'Anekal', 'Yelahanka'],
  },
  {
    name: 'Mysuru (Mysore)',
    code: 'KA-09/55',
    headquarters: 'Mysuru',
    center: { lat: 12.2958, lng: 76.6394 },
    taluks: ['Mysuru', 'Nanjangud', 'Hunsur', 'T. Narasipura', 'K.R. Nagar', 'Periyapatna', 'Saragur'],
  },
  {
    name: 'Dakshina Kannada (Mangaluru)',
    code: 'KA-19/20',
    headquarters: 'Mangaluru',
    center: { lat: 12.9141, lng: 74.8560 },
    taluks: ['Mangaluru', 'Bantwal', 'Belthangady', 'Puttur', 'Sullia', 'Moodbidri', 'Kadaba'],
  },
  {
    name: 'Dharwad (Hubballi-Dharwad)',
    code: 'KA-25',
    headquarters: 'Dharwad / Hubballi',
    center: { lat: 15.3647, lng: 75.1240 },
    taluks: ['Hubballi Urban', 'Hubballi Rural', 'Dharwad', 'Kundgol', 'Kalghatgi', 'Navalgund', 'Alnavar'],
  },
  {
    name: 'Belagavi (Belgaum)',
    code: 'KA-22/23/49',
    headquarters: 'Belagavi',
    center: { lat: 15.8497, lng: 74.4977 },
    taluks: ['Belagavi', 'Gokak', 'Chikodi', 'Athani', 'Bailhongal', 'Ramdurg', 'Saundatti', 'Hukkeri', 'Khanapur', 'Raybag', 'Nipani', 'Kagawad'],
  },
  {
    name: 'Kalaburagi (Gulbarga)',
    code: 'KA-32',
    headquarters: 'Kalaburagi',
    center: { lat: 17.3297, lng: 76.8343 },
    taluks: ['Kalaburagi', 'Aland', 'Afzalpur', 'Jevargi', 'Sedam', 'Chincholi', 'Chittapur', 'Kamalapur', 'Yadrami', 'Shahabad'],
  },
  {
    name: 'Shivamogga (Shimoga)',
    code: 'KA-14',
    headquarters: 'Shivamogga',
    center: { lat: 13.9299, lng: 75.5681 },
    taluks: ['Shivamogga', 'Bhadravathi', 'Sagar', 'Thirthahalli', 'Shikaripura', 'Soraba', 'Hosanagara'],
  },
  {
    name: 'Udupi',
    code: 'KA-20',
    headquarters: 'Udupi',
    center: { lat: 13.3409, lng: 74.7421 },
    taluks: ['Udupi', 'Kundapura', 'Karkala', 'Brahmavara', 'Byndoor', 'Kaup', 'Hebri'],
  },
  {
    name: 'Tumakuru (Tumkur)',
    code: 'KA-06',
    headquarters: 'Tumakuru',
    center: { lat: 13.3379, lng: 77.1010 },
    taluks: ['Tumakuru', 'Tiptur', 'Madhugiri', 'Kunigal', 'Sira', 'Pavagada', 'Gubbi', 'Chikkanayakanahalli', 'Turuvekere', 'Koratagere'],
  },
  {
    name: 'Ballari (Bellary)',
    code: 'KA-34',
    headquarters: 'Ballari',
    center: { lat: 15.1394, lng: 76.9214 },
    taluks: ['Ballari', 'Kurugodu', 'Kampli', 'Siruguppa', 'Sandur'],
  },
  {
    name: 'Davanagere',
    code: 'KA-17',
    headquarters: 'Davanagere',
    center: { lat: 14.4644, lng: 75.9218 },
    taluks: ['Davanagere', 'Harihara', 'Honnali', 'Channagiri', 'Jagalur', 'Nyamathi'],
  },
  {
    name: 'Hassan',
    code: 'KA-13',
    headquarters: 'Hassan',
    center: { lat: 13.0033, lng: 76.1004 },
    taluks: ['Hassan', 'Sakleshpur', 'Channarayapatna', 'Alur', 'Belur', 'Holenarasipura', 'Arkalgud', 'Arsikere'],
  },
  {
    name: 'Vijayapura (Bijapur)',
    code: 'KA-28',
    headquarters: 'Vijayapura',
    center: { lat: 16.8302, lng: 75.7100 },
    taluks: ['Vijayapura', 'Basavana Bagewadi', 'Indi', 'Muddebihal', 'Sindagi', 'Chadchan', 'Tikota', 'Babaleshwar', 'Kolhar', 'Talikoti'],
  },
  {
    name: 'Mandya',
    code: 'KA-11',
    headquarters: 'Mandya',
    center: { lat: 12.5218, lng: 76.8951 },
    taluks: ['Mandya', 'Maddur', 'Malavalli', 'Srirangapatna', 'Pandavapura', 'Nagamangala', 'Krishnarajpet'],
  },
  {
    name: 'Chikkamagaluru (Kadur/Chikmagalur)',
    code: 'KA-18',
    headquarters: 'Chikkamagaluru',
    center: { lat: 13.3161, lng: 75.7720 },
    taluks: ['Chikkamagaluru', 'Mudigere', 'Koppa', 'Sringeri', 'Narasimharajapura', 'Tarikere', 'Kadur', 'Ajjampura'],
  },
  {
    name: 'Kodagu (Coorg / Madikeri)',
    code: 'KA-12',
    headquarters: 'Madikeri',
    center: { lat: 12.4244, lng: 75.7382 },
    taluks: ['Madikeri', 'Virajpet', 'Somwarpet', 'Ponnampet', 'Kushalnagar'],
  },
  {
    name: 'Uttara Kannada (Karwar)',
    code: 'KA-30/31',
    headquarters: 'Karwar',
    center: { lat: 14.8135, lng: 74.1297 },
    taluks: ['Karwar', 'Ankola', 'Kumta', 'Honnavar', 'Bhatkal', 'Sirsi', 'Siddapur', 'Yellapur', 'Dandeli', 'Haliyal', 'Joida'],
  },
  {
    name: 'Kolar',
    code: 'KA-07',
    headquarters: 'Kolar',
    center: { lat: 13.1367, lng: 78.1291 },
    taluks: ['Kolar', 'Bangarapet', 'Malur', 'Mulbagal', 'Srinivaspur', 'KGF (Robertsonpet)'],
  },
  {
    name: 'Chikkaballapura',
    code: 'KA-40',
    headquarters: 'Chikkaballapura',
    center: { lat: 13.4325, lng: 77.7275 },
    taluks: ['Chikkaballapura', 'Gauribidanur', 'Bagepalli', 'Sidlaghatta', 'Chintamani', 'Gudibande'],
  },
  {
    name: 'Ramanagara',
    code: 'KA-42',
    headquarters: 'Ramanagara',
    center: { lat: 12.7150, lng: 77.2811 },
    taluks: ['Ramanagara', 'Channapatna', 'Kanakapura', 'Magadi', 'Harohalli'],
  },
  {
    name: 'Chamarajanagar',
    code: 'KA-10',
    headquarters: 'Chamarajanagar',
    center: { lat: 11.9261, lng: 76.9437 },
    taluks: ['Chamarajanagar', 'Gundlupet', 'Kollegal', 'Yelandur', 'Hanur'],
  },
  {
    name: 'Bagalkote',
    code: 'KA-29',
    headquarters: 'Bagalkote',
    center: { lat: 16.1691, lng: 75.6615 },
    taluks: ['Bagalkote', 'Badami', 'Hungund', 'Jamkhandi', 'Mudhol', 'Bilagi', 'Ilkal', 'Rabkavi Banhatti', 'Guledagudda'],
  },
  {
    name: 'Gadag',
    code: 'KA-26',
    headquarters: 'Gadag',
    center: { lat: 15.4313, lng: 75.6318 },
    taluks: ['Gadag', 'Ron', 'Shirhatti', 'Mundargi', 'Nargund', 'Gajendragad', 'Lakshmeshwar'],
  },
  {
    name: 'Haveri',
    code: 'KA-27',
    headquarters: 'Haveri',
    center: { lat: 14.7954, lng: 75.4024 },
    taluks: ['Haveri', 'Ranebennur', 'Byadgi', 'Hirekerur', 'Shiggaon', 'Savanur', 'Hangal', 'Rattihalli'],
  },
  {
    name: 'Koppal',
    code: 'KA-37',
    headquarters: 'Koppal',
    center: { lat: 15.3556, lng: 76.1557 },
    taluks: ['Koppal', 'Gangavathi', 'Kushtagi', 'Yelburga', 'Kanakagiri', 'Karatagi', 'Kukanur'],
  },
  {
    name: 'Raichur',
    code: 'KA-36',
    headquarters: 'Raichur',
    center: { lat: 16.2120, lng: 77.3439 },
    taluks: ['Raichur', 'Manvi', 'Sindhanur', 'Devadurga', 'Lingsugur', 'Maski', 'Sirwar'],
  },
  {
    name: 'Bidar',
    code: 'KA-38',
    headquarters: 'Bidar',
    center: { lat: 17.9104, lng: 77.5199 },
    taluks: ['Bidar', 'Basavakalyan', 'Bhalki', 'Homnabad', 'Aurad', 'Kamalnagar', 'Chitaguppa', 'Hulsoor'],
  },
  {
    name: 'Yadgir',
    code: 'KA-33',
    headquarters: 'Yadgir',
    center: { lat: 16.7621, lng: 77.1378 },
    taluks: ['Yadgir', 'Shahapur', 'Shorapur', 'Hunsagi', 'Gurmatkal', 'Wadagera'],
  },
  {
    name: 'Vijayanagara (Hosapete)',
    code: 'KA-35',
    headquarters: 'Hosapete',
    center: { lat: 15.2689, lng: 76.3909 },
    taluks: ['Hosapete', 'Hagaribommanahalli', 'Harapanahalli', 'Hoovina Hadagali', 'Kudligi', 'Kotturu'],
  },
];

/**
 * Real Multi-Specialty & Government Tertiary Care Hospitals in Karnataka
 */
export const KARNATAKA_REAL_HOSPITALS: Hospital[] = [
  // --- BENGALURU ---
  {
    id: 'hosp-ka-blr-01',
    name: 'Victoria Hospital & BMCRI Emergency Trauma Care Centre',
    address: 'Fort Road, K.R. Market, Kalasipalya, Bengaluru 560002',
    location: { lat: 12.9629, lng: 77.5753 },
    sector: 'Bengaluru South - K.R. Market Hub',
    phone: '080-26701150 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 45,
    availableIcu: 12,
    generalBedsCapacity: 950,
    availableGeneralBeds: 180,
    traumaCenter: true,
    cardiology: true,
    neurology: true,
    pediatrics: true,
    burnUnit: true, // Renowned Mahabodhi Burns Centre
    ambulanceSupport: true,
    waitTimeMinutes: 4,
  },
  {
    id: 'hosp-ka-blr-02',
    name: 'NIMHANS (National Institute of Mental Health & Neurosciences)',
    address: 'Hosur Road, Lakkasandra, Wilson Garden, Bengaluru 560029',
    location: { lat: 12.9432, lng: 77.5959 },
    sector: 'Bengaluru Central - Hosur Road Corridor',
    phone: '080-26995000 / 080-26995555',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 35,
    availableIcu: 9,
    generalBedsCapacity: 650,
    availableGeneralBeds: 85,
    traumaCenter: true,
    cardiology: false,
    neurology: true, // World-class neuro-trauma casualty
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 5,
  },
  {
    id: 'hosp-ka-blr-03',
    name: 'Sri Jayadeva Institute of Cardiovascular Sciences & Research',
    address: 'Bannerghatta Main Road, 9th Block, Jayanagar, Bengaluru 560069',
    location: { lat: 12.9231, lng: 77.5985 },
    sector: 'Bengaluru South - Jayanagar',
    phone: '080-22977400 / 080-22977200',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 60,
    availableIcu: 16,
    generalBedsCapacity: 1150,
    availableGeneralBeds: 210,
    traumaCenter: false,
    cardiology: true, // Premier Cardiology & Cath Lab Center of Excellence in South Asia
    neurology: false,
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 3,
  },
  {
    id: 'hosp-ka-blr-04',
    name: 'Manipal Hospital HAL Airport Road',
    address: '98, HAL Old Airport Rd, Kodihalli, Bengaluru 560017',
    location: { lat: 12.9592, lng: 77.6483 },
    sector: 'Bengaluru East - Indiranagar / HAL',
    phone: '080-25024444 / 080-25023344',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 38,
    availableIcu: 8,
    generalBedsCapacity: 600,
    availableGeneralBeds: 75,
    traumaCenter: true,
    cardiology: true,
    neurology: true,
    pediatrics: true,
    burnUnit: true,
    ambulanceSupport: true,
    waitTimeMinutes: 6,
  },
  {
    id: 'hosp-ka-blr-05',
    name: 'Narayana Health City (Mazumdar Shaw Medical Centre)',
    address: '258/A, Bommasandra Industrial Area, Anekal Taluk, Bengaluru 560099',
    location: { lat: 12.8091, lng: 77.6974 },
    sector: 'Bengaluru South - Electronic City / Anekal',
    phone: '080-71222222 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 50,
    availableIcu: 14,
    generalBedsCapacity: 1400,
    availableGeneralBeds: 290,
    traumaCenter: true,
    cardiology: true,
    neurology: true,
    pediatrics: true,
    burnUnit: true,
    ambulanceSupport: true,
    waitTimeMinutes: 5,
  },
  {
    id: 'hosp-ka-blr-06',
    name: 'Bowring & Lady Curzon Hospital',
    address: 'Lady Curzon Rd, Tasker Town, Shivajinagar, Bengaluru 560001',
    location: { lat: 12.9830, lng: 77.6033 },
    sector: 'Bengaluru Central - Shivajinagar / MG Road',
    phone: '080-25591325',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 25,
    availableIcu: 6,
    generalBedsCapacity: 686,
    availableGeneralBeds: 110,
    traumaCenter: true,
    cardiology: true,
    neurology: false,
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 7,
  },

  // --- MYSURU ---
  {
    id: 'hosp-ka-mys-01',
    name: 'K.R. Hospital (Krishna Rajendra Hospital - MMCRI)',
    address: 'Sayyaji Rao Road, Near Mysuru Palace, Agrahara, Mysuru 570001',
    location: { lat: 12.3148, lng: 76.6492 },
    sector: 'Mysuru City Center',
    phone: '0821-2520512 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 30,
    availableIcu: 7,
    generalBedsCapacity: 1050,
    availableGeneralBeds: 160,
    traumaCenter: true,
    cardiology: true,
    neurology: true,
    pediatrics: true,
    burnUnit: true,
    ambulanceSupport: true,
    waitTimeMinutes: 5,
  },
  {
    id: 'hosp-ka-mys-02',
    name: 'Apollo BGS Hospitals Mysuru',
    address: 'Adichunchanagiri Road, Kuvempunagar, Mysuru 570023',
    location: { lat: 12.2882, lng: 76.6263 },
    sector: 'Mysuru West - Kuvempunagar',
    phone: '0821-2568888 / 1066',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 24,
    availableIcu: 5,
    generalBedsCapacity: 210,
    availableGeneralBeds: 38,
    traumaCenter: true,
    cardiology: true,
    neurology: true,
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 6,
  },
  {
    id: 'hosp-ka-mys-03',
    name: 'Sri Jayadeva Institute of Cardiology Mysuru Branch',
    address: 'KRS Road, PK Sanatorium Compound, Mysuru 570016',
    location: { lat: 12.3456, lng: 76.6234 },
    sector: 'Mysuru North - KRS Road Corridor',
    phone: '0821-2336336',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 28,
    availableIcu: 8,
    generalBedsCapacity: 350,
    availableGeneralBeds: 60,
    traumaCenter: false,
    cardiology: true, // Dedicated Heart Emergency
    neurology: false,
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 3,
  },

  // --- MANGALURU (DAKSHINA KANNADA) ---
  {
    id: 'hosp-ka-mng-01',
    name: 'Government Wenlock District Hospital',
    address: 'Hampankatta, Near Railway Station, Mangaluru 575001',
    location: { lat: 12.8688, lng: 74.8428 },
    sector: 'Mangaluru Central - Hampankatta',
    phone: '0824-2424444 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 25,
    availableIcu: 6,
    generalBedsCapacity: 900,
    availableGeneralBeds: 140,
    traumaCenter: true,
    cardiology: true,
    neurology: true,
    pediatrics: true,
    burnUnit: true,
    ambulanceSupport: true,
    waitTimeMinutes: 5,
  },
  {
    id: 'hosp-ka-mng-02',
    name: 'KMC Hospital Mangaluru (Kasturba Medical College)',
    address: 'Ambedkar Circle, Balmatta Road, Mangaluru 575001',
    location: { lat: 12.8732, lng: 74.8465 },
    sector: 'Mangaluru City - Balmatta',
    phone: '0824-2444590',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 32,
    availableIcu: 8,
    generalBedsCapacity: 450,
    availableGeneralBeds: 70,
    traumaCenter: true,
    cardiology: true,
    neurology: true,
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 4,
  },

  // --- HUBBALLI-DHARWAD ---
  {
    id: 'hosp-ka-hbl-01',
    name: 'Karnataka Institute of Medical Sciences (KIMS Hospital)',
    address: 'Vidyanagar, PB Road, Hubballi 580022',
    location: { lat: 15.3585, lng: 75.1325 },
    sector: 'Hubballi Central - Vidyanagar Corridor',
    phone: '0836-2272044 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 35,
    availableIcu: 9,
    generalBedsCapacity: 1200,
    availableGeneralBeds: 220,
    traumaCenter: true,
    cardiology: true,
    neurology: true,
    pediatrics: true,
    burnUnit: true,
    ambulanceSupport: true,
    waitTimeMinutes: 5,
  },
  {
    id: 'hosp-ka-dhw-02',
    name: 'SDM College of Medical Sciences & Hospital',
    address: 'Manjushree Nagar, Sattur, Dharwad 580009',
    location: { lat: 15.4052, lng: 75.0594 },
    sector: 'Dharwad - Sattur Bypass',
    phone: '0836-2477777',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 28,
    availableIcu: 7,
    generalBedsCapacity: 800,
    availableGeneralBeds: 110,
    traumaCenter: true,
    cardiology: true,
    neurology: true,
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 6,
  },

  // --- BELAGAVI ---
  {
    id: 'hosp-ka-bgm-01',
    name: 'Belagavi Institute of Medical Sciences (BIMS / Civil Hospital)',
    address: 'Dr. B.R. Ambedkar Road, Sadashiv Nagar, Belagavi 590001',
    location: { lat: 15.8572, lng: 74.5098 },
    sector: 'Belagavi Central',
    phone: '0831-2421464 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 24,
    availableIcu: 5,
    generalBedsCapacity: 750,
    availableGeneralBeds: 95,
    traumaCenter: true,
    cardiology: true,
    neurology: true,
    pediatrics: true,
    burnUnit: true,
    ambulanceSupport: true,
    waitTimeMinutes: 6,
  },
  {
    id: 'hosp-ka-bgm-02',
    name: 'KLE Dr. Prabhakar Kore Hospital & Medical Research Centre',
    address: 'Nehru Nagar, National Highway 4, Belagavi 590010',
    location: { lat: 15.8821, lng: 74.5244 },
    sector: 'Belagavi North - NH4 Corridor',
    phone: '0831-2473777',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 40,
    availableIcu: 11,
    generalBedsCapacity: 1200,
    availableGeneralBeds: 210,
    traumaCenter: true,
    cardiology: true,
    neurology: true,
    pediatrics: true,
    burnUnit: true,
    ambulanceSupport: true,
    waitTimeMinutes: 4,
  },

  // --- KALABURAGI (GULBARGA) ---
  {
    id: 'hosp-ka-klb-01',
    name: 'Gulbarga Institute of Medical Sciences (GIMS Hospital)',
    address: 'Sedam Road, Veeresh Nagar, Kalaburagi 585105',
    location: { lat: 17.3225, lng: 76.8482 },
    sector: 'Kalaburagi - Sedam Road Hub',
    phone: '08472-278601 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 22,
    availableIcu: 6,
    generalBedsCapacity: 750,
    availableGeneralBeds: 105,
    traumaCenter: true,
    cardiology: true,
    neurology: true,
    pediatrics: true,
    burnUnit: true,
    ambulanceSupport: true,
    waitTimeMinutes: 5,
  },

  // --- SHIVAMOGGA ---
  {
    id: 'hosp-ka-smg-01',
    name: 'Shimoga Institute of Medical Sciences (McGann District Hospital)',
    address: 'Sagar Road, Shivamogga 577201',
    location: { lat: 13.9351, lng: 75.5654 },
    sector: 'Shivamogga Central - Sagar Road',
    phone: '08182-229933 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 20,
    availableIcu: 4,
    generalBedsCapacity: 700,
    availableGeneralBeds: 80,
    traumaCenter: true,
    cardiology: true,
    neurology: true,
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 6,
  },

  // --- UDUPI ---
  {
    id: 'hosp-ka-udp-01',
    name: 'Kasturba Hospital Manipal (KMC Manipal)',
    address: 'Madhav Nagar, Tiger Circle, Manipal, Udupi 576104',
    location: { lat: 13.3533, lng: 74.7854 },
    sector: 'Udupi - Manipal Campus',
    phone: '0820-2922761 / 0820-2571201',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 35,
    availableIcu: 9,
    generalBedsCapacity: 1200,
    availableGeneralBeds: 180,
    traumaCenter: true,
    cardiology: true,
    neurology: true,
    pediatrics: true,
    burnUnit: true,
    ambulanceSupport: true,
    waitTimeMinutes: 4,
  },

  // --- BALLARI ---
  {
    id: 'hosp-ka-blr-vims',
    name: 'Vijayanagar Institute of Medical Sciences (VIMS Hospital)',
    address: 'Cantonment, Ballari 583104',
    location: { lat: 15.1325, lng: 76.9112 },
    sector: 'Ballari Cantonment',
    phone: '08392-235201 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 20,
    availableIcu: 5,
    generalBedsCapacity: 680,
    availableGeneralBeds: 90,
    traumaCenter: true,
    cardiology: true,
    neurology: false,
    pediatrics: true,
    burnUnit: true,
    ambulanceSupport: true,
    waitTimeMinutes: 7,
  },

  // --- DAVANAGERE ---
  {
    id: 'hosp-ka-dvg-01',
    name: 'J.J.M. Medical College & Bapuji Hospital',
    address: 'MCC B Block, Davanagere 577004',
    location: { lat: 14.4712, lng: 75.9185 },
    sector: 'Davanagere Central',
    phone: '08192-231388 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 22,
    availableIcu: 6,
    generalBedsCapacity: 850,
    availableGeneralBeds: 120,
    traumaCenter: true,
    cardiology: true,
    neurology: true,
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 5,
  },

  // --- HASSAN ---
  {
    id: 'hosp-ka-hsn-01',
    name: 'Hassan Institute of Medical Sciences (HIMS District Hospital)',
    address: 'Sri Chamarajendra Hospital Compound, Hassan 573201',
    location: { lat: 13.0078, lng: 76.0965 },
    sector: 'Hassan Central',
    phone: '08172-231699 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 18,
    availableIcu: 4,
    generalBedsCapacity: 600,
    availableGeneralBeds: 75,
    traumaCenter: true,
    cardiology: true,
    neurology: false,
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 6,
  },

  // --- TUMAKURU ---
  {
    id: 'hosp-ka-tmk-01',
    name: 'District Government Hospital & Trauma Care Tumakuru',
    address: 'B.H. Road, Ashok Nagar, Tumakuru 572102',
    location: { lat: 13.3421, lng: 77.1054 },
    sector: 'Tumakuru - B.H. Road Corridor',
    phone: '0816-2278385 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 16,
    availableIcu: 3,
    generalBedsCapacity: 450,
    availableGeneralBeds: 50,
    traumaCenter: true,
    cardiology: true,
    neurology: false,
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 7,
  },

  // --- VIJAYAPURA ---
  {
    id: 'hosp-ka-vjp-01',
    name: 'Al-Ameen Medical College Hospital & District Hospital Vijayapura',
    address: 'Athani Road, Vijayapura 586108',
    location: { lat: 16.8302, lng: 75.7100 },
    sector: 'Vijayapura Central',
    phone: '08352-270055 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 20,
    availableIcu: 5,
    generalBedsCapacity: 650,
    availableGeneralBeds: 85,
    traumaCenter: true,
    cardiology: true,
    neurology: false,
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 5,
  },

  // --- MANDYA ---
  {
    id: 'hosp-ka-mnd-01',
    name: 'Mandya Institute of Medical Sciences (MIMS Hospital)',
    address: 'Bengaluru-Mysuru Highway, Mandya 571401',
    location: { lat: 12.5218, lng: 76.8951 },
    sector: 'Mandya - Highway Corridor',
    phone: '08232-222086 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 24,
    availableIcu: 6,
    generalBedsCapacity: 750,
    availableGeneralBeds: 110,
    traumaCenter: true,
    cardiology: true,
    neurology: true,
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 4,
  },

  // --- CHIKKAMAGALURU ---
  {
    id: 'hosp-ka-ckm-01',
    name: 'Chikkamagaluru Institute of Medical Sciences (CIMS)',
    address: 'K.M. Road, Chikkamagaluru 577101',
    location: { lat: 13.3161, lng: 75.7720 },
    sector: 'Chikkamagaluru Central',
    phone: '08262-230230 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 18,
    availableIcu: 4,
    generalBedsCapacity: 500,
    availableGeneralBeds: 65,
    traumaCenter: true,
    cardiology: true,
    neurology: false,
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 6,
  },

  // --- KODAGU (MADIKERI) ---
  {
    id: 'hosp-ka-kdg-01',
    name: 'Kodagu Institute of Medical Sciences (KoIMS District Hospital)',
    address: 'Stuart Hill, Madikeri, Kodagu 571201',
    location: { lat: 12.4244, lng: 75.7382 },
    sector: 'Kodagu - Madikeri Hills',
    phone: '08272-225444 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 16,
    availableIcu: 4,
    generalBedsCapacity: 450,
    availableGeneralBeds: 70,
    traumaCenter: true,
    cardiology: false,
    neurology: false,
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 5,
  },

  // --- UTTARA KANNADA (KARWAR) ---
  {
    id: 'hosp-ka-uk-01',
    name: 'Karwar Institute of Medical Sciences (KRIMS Hospital)',
    address: 'MG Road, Karwar 581301',
    location: { lat: 14.8135, lng: 74.1297 },
    sector: 'Karwar Coastline',
    phone: '08382-226210 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 20,
    availableIcu: 5,
    generalBedsCapacity: 550,
    availableGeneralBeds: 80,
    traumaCenter: true,
    cardiology: true,
    neurology: false,
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 6,
  },

  // --- KOLAR ---
  {
    id: 'hosp-ka-klr-01',
    name: 'R.L. Jalappa Hospital & SNR District Hospital Kolar',
    address: 'Tamaka, Kolar 563103',
    location: { lat: 13.1367, lng: 78.1291 },
    sector: 'Kolar - Tamaka NH-75',
    phone: '08152-243003 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 25,
    availableIcu: 7,
    generalBedsCapacity: 800,
    availableGeneralBeds: 130,
    traumaCenter: true,
    cardiology: true,
    neurology: true,
    pediatrics: true,
    burnUnit: true,
    ambulanceSupport: true,
    waitTimeMinutes: 4,
  },

  // --- CHIKKABALLAPURA ---
  {
    id: 'hosp-ka-ckb-01',
    name: 'Chikkaballapura Institute of Medical Sciences (CIMS)',
    address: 'District Hospital Campus, Chikkaballapura 562101',
    location: { lat: 13.4325, lng: 77.7275 },
    sector: 'Chikkaballapura NH-44',
    phone: '08156-272022 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 18,
    availableIcu: 4,
    generalBedsCapacity: 500,
    availableGeneralBeds: 75,
    traumaCenter: true,
    cardiology: true,
    neurology: false,
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 5,
  },

  // --- RAMANAGARA ---
  {
    id: 'hosp-ka-rmn-01',
    name: 'Ramanagara District Hospital & Trauma Care Center',
    address: 'Ijoor, Bengaluru-Mysuru Expressway, Ramanagara 562159',
    location: { lat: 12.7150, lng: 77.2811 },
    sector: 'Ramanagara Expressway Hub',
    phone: '080-27271234 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 20,
    availableIcu: 5,
    generalBedsCapacity: 450,
    availableGeneralBeds: 60,
    traumaCenter: true,
    cardiology: true,
    neurology: false,
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 4,
  },

  // --- CHAMARAJANAGAR ---
  {
    id: 'hosp-ka-crn-01',
    name: 'Chamarajanagar Institute of Medical Sciences (CIMS)',
    address: 'B.R. Hills Road, Yeda Halli, Chamarajanagar 571313',
    location: { lat: 11.9261, lng: 76.9437 },
    sector: 'Chamarajanagar Central',
    phone: '08226-222076 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 18,
    availableIcu: 4,
    generalBedsCapacity: 480,
    availableGeneralBeds: 70,
    traumaCenter: true,
    cardiology: false,
    neurology: false,
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 6,
  },

  // --- BAGALKOTE ---
  {
    id: 'hosp-ka-bgk-01',
    name: 'S.N. Medical College & H.S.K. Hospital Bagalkote',
    address: 'Navanagar, Bagalkote 587102',
    location: { lat: 16.1691, lng: 75.6615 },
    sector: 'Bagalkote Navanagar',
    phone: '08354-235360 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 28,
    availableIcu: 7,
    generalBedsCapacity: 850,
    availableGeneralBeds: 125,
    traumaCenter: true,
    cardiology: true,
    neurology: true,
    pediatrics: true,
    burnUnit: true,
    ambulanceSupport: true,
    waitTimeMinutes: 5,
  },

  // --- GADAG ---
  {
    id: 'hosp-ka-gdg-01',
    name: 'Gadag Institute of Medical Sciences (GIMS Hospital)',
    address: 'Mallisamudra, Gadag 582103',
    location: { lat: 15.4313, lng: 75.6318 },
    sector: 'Gadag - Hubballi Road',
    phone: '08372-237410 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 20,
    availableIcu: 5,
    generalBedsCapacity: 550,
    availableGeneralBeds: 90,
    traumaCenter: true,
    cardiology: true,
    neurology: false,
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 5,
  },

  // --- HAVERI ---
  {
    id: 'hosp-ka-hvr-01',
    name: 'Haveri Institute of Medical Sciences (HIMS District Hospital)',
    address: 'B.H. Road, Haveri 581110',
    location: { lat: 14.7954, lng: 75.4024 },
    sector: 'Haveri Central NH-48',
    phone: '08375-232400 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 18,
    availableIcu: 4,
    generalBedsCapacity: 500,
    availableGeneralBeds: 75,
    traumaCenter: true,
    cardiology: true,
    neurology: false,
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 5,
  },

  // --- KOPPAL ---
  {
    id: 'hosp-ka-kpl-01',
    name: 'Koppal Institute of Medical Sciences (KIMS Hospital)',
    address: 'Kalyani Nagara, Koppal 583231',
    location: { lat: 15.3556, lng: 76.1557 },
    sector: 'Koppal Central',
    phone: '08539-225025 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 18,
    availableIcu: 4,
    generalBedsCapacity: 480,
    availableGeneralBeds: 70,
    traumaCenter: true,
    cardiology: true,
    neurology: false,
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 6,
  },

  // --- RAICHUR ---
  {
    id: 'hosp-ka-rcr-01',
    name: 'Raichur Institute of Medical Sciences (RIMS & OPEC Hospital)',
    address: 'Hyderabad Road, Raichur 584102',
    location: { lat: 16.2120, lng: 77.3439 },
    sector: 'Raichur - Hyderabad Road',
    phone: '08532-235488 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 26,
    availableIcu: 7,
    generalBedsCapacity: 750,
    availableGeneralBeds: 120,
    traumaCenter: true,
    cardiology: true,
    neurology: true,
    pediatrics: true,
    burnUnit: true,
    ambulanceSupport: true,
    waitTimeMinutes: 4,
  },

  // --- BIDAR ---
  {
    id: 'hosp-ka-bdr-01',
    name: 'Bidar Institute of Medical Sciences (BRIMS Hospital)',
    address: 'Udgir Road, Bidar 585401',
    location: { lat: 17.9104, lng: 77.5199 },
    sector: 'Bidar Central',
    phone: '08482-228366 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 22,
    availableIcu: 6,
    generalBedsCapacity: 650,
    availableGeneralBeds: 95,
    traumaCenter: true,
    cardiology: true,
    neurology: false,
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 5,
  },

  // --- YADGIR ---
  {
    id: 'hosp-ka-ydg-01',
    name: 'Yadgir Institute of Medical Sciences (YIMS Hospital)',
    address: 'Chittapur Road, Mudnal, Yadgir 585202',
    location: { lat: 16.7621, lng: 77.1378 },
    sector: 'Yadgir Mudnal Hub',
    phone: '08473-253700 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 16,
    availableIcu: 4,
    generalBedsCapacity: 450,
    availableGeneralBeds: 60,
    traumaCenter: true,
    cardiology: false,
    neurology: false,
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 6,
  },

  // --- VIJAYANAGARA (HOSAPETE) ---
  {
    id: 'hosp-ka-vnr-01',
    name: '100-Bed Government General Hospital Hosapete',
    address: 'Station Road, Hosapete, Vijayanagara 583201',
    location: { lat: 15.2689, lng: 76.3909 },
    sector: 'Hosapete - Hampi Junction',
    phone: '08394-228222 / 108',
    status: 'available',
    emergencyAvailable: true,
    icuCapacity: 16,
    availableIcu: 4,
    generalBedsCapacity: 400,
    availableGeneralBeds: 55,
    traumaCenter: true,
    cardiology: true,
    neurology: false,
    pediatrics: true,
    burnUnit: false,
    ambulanceSupport: true,
    waitTimeMinutes: 5,
  },
];

/**
 * 108 Arogya Kavacha Karnataka Ambulance Fleet
 */
export const KARNATAKA_108_AMBULANCES: Ambulance[] = [
  {
    id: 'amb-ka-101',
    vehicleNumber: 'KA-01-G-1081 (108 ALS)',
    driverName: 'Manjunath Gowda',
    driverPhone: '98451 10801',
    type: 'ALS',
    status: 'available',
    location: { lat: 12.9665, lng: 77.5812 },
    sector: 'Bengaluru - Majestic / K.R. Market Station',
    fuelPercent: 92,
    equipmentScore: 99,
  },
  {
    id: 'amb-ka-102',
    vehicleNumber: 'KA-05-G-1082 (108 ALS)',
    driverName: 'Suresh Kumar',
    driverPhone: '98451 10802',
    type: 'ALS',
    status: 'en_route',
    location: { lat: 12.9341, lng: 77.6102 },
    sector: 'Bengaluru - Koramangala / Jayanagar',
    fuelPercent: 88,
    equipmentScore: 98,
    currentDestination: 'Jayadeva Cardiac Emergency',
    etaMinutes: 4,
  },
  {
    id: 'amb-ka-103',
    vehicleNumber: 'KA-03-G-1083 (108 BLS)',
    driverName: 'Prashanth Hegde',
    driverPhone: '98451 10803',
    type: 'BLS',
    status: 'available',
    location: { lat: 12.9782, lng: 77.6405 },
    sector: 'Bengaluru - Indiranagar / Old Airport Road',
    fuelPercent: 85,
    equipmentScore: 94,
  },
  {
    id: 'amb-ka-104',
    vehicleNumber: 'KA-51-G-1084 (108 Neonatal)',
    driverName: 'Basavaraj Patil',
    driverPhone: '98451 10804',
    type: 'Neonatal',
    status: 'available',
    location: { lat: 12.8398, lng: 77.6789 },
    sector: 'Bengaluru - Electronic City NH-44',
    fuelPercent: 95,
    equipmentScore: 100,
  },
  {
    id: 'amb-ka-105',
    vehicleNumber: 'KA-09-G-1085 (108 ALS)',
    driverName: 'Raghavendra Rao',
    driverPhone: '98451 10805',
    type: 'ALS',
    status: 'available',
    location: { lat: 12.3082, lng: 76.6412 },
    sector: 'Mysuru - K.R. Hospital Substation',
    fuelPercent: 90,
    equipmentScore: 97,
  },
  {
    id: 'amb-ka-106',
    vehicleNumber: 'KA-19-G-1086 (108 ALS)',
    driverName: 'Dinesh Poojary',
    driverPhone: '98451 10806',
    type: 'ALS',
    status: 'available',
    location: { lat: 12.8712, lng: 74.8491 },
    sector: 'Mangaluru - Wenlock Emergency Bay',
    fuelPercent: 94,
    equipmentScore: 98,
  },
  {
    id: 'amb-ka-107',
    vehicleNumber: 'KA-25-G-1087 (108 ALS)',
    driverName: 'Mallikarjun Hiremath',
    driverPhone: '98451 10807',
    type: 'ALS',
    status: 'available',
    location: { lat: 15.3610, lng: 75.1298 },
    sector: 'Hubballi - KIMS Trauma Outpost',
    fuelPercent: 87,
    equipmentScore: 96,
  },
  {
    id: 'amb-ka-108',
    vehicleNumber: 'KA-22-G-1088 (108 ALS)',
    driverName: 'Anand Shinde',
    driverPhone: '98451 10808',
    type: 'ALS',
    status: 'available',
    location: { lat: 15.8612, lng: 74.5120 },
    sector: 'Belagavi - BIMS Civil Depot',
    fuelPercent: 89,
    equipmentScore: 95,
  },
  {
    id: 'amb-ka-109',
    vehicleNumber: 'KA-32-G-1089 (108 BLS)',
    driverName: 'Mohammed Ismail',
    driverPhone: '98451 10809',
    type: 'BLS',
    status: 'available',
    location: { lat: 17.3265, lng: 76.8421 },
    sector: 'Kalaburagi - GIMS Emergency Post',
    fuelPercent: 82,
    equipmentScore: 93,
  },
  {
    id: 'amb-ka-110',
    vehicleNumber: 'KA-14-G-1090 (108 ALS)',
    driverName: 'Naveen Kumar K.M.',
    driverPhone: '98451 10810',
    type: 'ALS',
    status: 'available',
    location: { lat: 13.9312, lng: 75.5670 },
    sector: 'Shivamogga - McGann Hospital Station',
    fuelPercent: 91,
    equipmentScore: 96,
  },
];
